// GENERATED BY cloud_templates.sh add service:ssm
import {
  SSMClient,
  PutParameterCommand,
  GetParameterCommand,
  DeleteParameterCommand,
} from '@aws-sdk/client-ssm';
import { KeyValueStore } from '../../types';

/**
 * SsmService
 *
 * Purpose:
 *   Thin, testable adapter around AWS SDK calls for Ssm.
 *
 * Notes:
 *   - Keep AWS SDK calls here (no orchestration).
 *   - Keep methods small and composable.
 */
export class SsmService implements KeyValueStore {
  /**
   * Create a system manager client instance.
   * @param client
   */
  constructor(private readonly client: SSMClient) {}

  async put(
    key: string,
    value: string,
    opts?: { contentType?: 'String' | 'SecureString'; description?: string },
  ): Promise<void> {
    if (!key || !value) {
      throw new Error('Parameter name and value are required');
    }
    const command = new PutParameterCommand({
      Name: key,
      Value: value,
      Type: opts?.contentType || 'String',
      Overwrite: true,
    });
    await this.client.send(command);
  }

  async get(key: string): Promise<string | undefined> {
    if (!key) {
      throw new Error('Parameter name is required');
    }
    const command = new GetParameterCommand({
      Name: key,
      WithDecryption: true,
    });
    const response = await this.client.send(command);
    return response.Parameter?.Value || '';
  }

  /**
   * Delete a parameter from SSM Parameter Store.
   * @param name The name of the parameter.
   */
  public async deleteParameter(name: string): Promise<void> {
    if (!name) {
      throw new Error('Parameter name is required');
    }
    const command = new DeleteParameterCommand({
      Name: name,
    });
    await this.client.send(command);
  }
}
