// GENERATED BY cloud_templates.sh add orchestrator:platform-config
import type { Cloud, IPlatformOperations, ProcessMap } from '../types';

/**
 * PlatformConfigOrchestrator
 *
 * Purpose:
 *   Orchestrates a workflow (runbook-style automation) using cloud services.
 *
 * Notes:
 *   - Put workflow coordination here.
 *   - Keep raw AWS SDK calls inside lib/aws/*Service.
 *   - Prefer small steps for testability.
 */


export class PlatformConfigOrchestrator {
  private readonly cloud: Cloud;
  private readonly processes: ProcessMap;

  constructor(private readonly ops: IPlatformOperations) {
    this.cloud = ops.cloud;

    // Arrow functions capture `this` safely
    this.processes = {
      aws: async () => {
        if (!this.ops.awsBootstrap){
          throw new Error('awsBootstrap is not configured');
        }
        this.ops.awsBootstrap.run();    
      },
      azure: async () => {
        if (!this.ops.azureBootstrap)
          throw new Error('azureBootstrap is not configured');
        await this.ops.azureBootstrap.run();
      },
      gcp: async () => {
        if (!this.ops.gcpBootstrap)
          throw new Error('gcpBootstrap is not configured');
        await this.ops.gcpBootstrap.run();
      },
    };
  }

  /** Initialize platform configuration for the selected cloud. */
  public async initialize(): Promise<void> {
    await this.processes[this.cloud]();
  }
}