// GENERATED BY cloud_templates.sh add service:ssm
import { SSMClient, PutParameterCommand, SendCommandCommand, GetParameterCommand, DeleteParameterCommand } from '@aws-sdk/client-ssm';

/**
 * SsmService
 *
 * Purpose:
 *   Thin, testable adapter around AWS SDK calls for Ssm.
 *
 * Notes:
 *   - Keep AWS SDK calls here (no orchestration).
 *   - Keep methods small and composable.
 */
export class SsmService {
  /**
   * Create a system manager client instance.
   * @param client 
   */
  constructor(private readonly client: SSMClient) {}

  /**
   * Create a new parameter in SSM Parameter Store.
   * @param name The name of the parameter.
   * @param value The value of the parameter.
   * @param type The type of the parameter ('String', 'SecureString', or 'StringList').
   */
  public async createParameter(name: string, value: string, type: 'String' | 'SecureString' | 'StringList'): Promise<void> {
    if(!name || !value) {
      throw new Error('Parameter name and value are required');
    }
    const command = new PutParameterCommand({
      Name: name,
      Value: value,
      Type: type,
      Overwrite: true, 
    });
    await this.client.send(command);
  }

  /**
   * Retrieve a parameter value from SSM Parameter Store.
   * @param name The name of the parameter.
   * @returns The value of the parameter.
   */
  public async getParameter(name: string): Promise<string> {
    if(!name) {
      throw new Error('Parameter name is required');
    }
    const command = new GetParameterCommand({
      Name: name,
      WithDecryption: true, 
    });
    const response = await this.client.send(command);
    return response.Parameter?.Value || '';
  }

  /**
   * Delete a parameter from SSM Parameter Store.
   * @param name The name of the parameter.
   */
  public async deleteParameter(name: string): Promise<void> {
    if(!name) {
      throw new Error('Parameter name is required');
    }
    const command = new DeleteParameterCommand({
      Name: name,
    });
    await this.client.send(command);
  }
}