// GENERATED BY cloud_templates.sh add service:ssm
import { SSMClient } from '@aws-sdk/client-ssm';

/**
 * SsmService
 *
 * Purpose:
 *   Thin, testable adapter around AWS SDK calls for Ssm.
 *
 * Notes:
 *   - Keep AWS SDK calls here (no orchestration).
 *   - Keep methods small and composable.
 */
export class SsmService {
  constructor(private readonly client: SSMClient) {
    // Initialize the service
  }
}